version: '2'

services:
    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/django/Dockerfile
        ports:
            - "8000:8000"
        expose:
            - 8000