# Generated by Django 4.1.2 on 2022-12-31 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1023)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AnalyzeSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2047)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('site_data', models.JSONField()),
                ('fetched_infos', models.JSONField(default=[])),
                ('to_contact_user', models.BooleanField(default=False)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contactuser')),
            ],
        ),
    ]
